# NumPy Cookbook

Working with matrices, arrays and vectors

In [1]:
import numpy as np

## 1.1 Creating vector

Creating as a ROW and as a COLUMN

In [6]:
vector_row = np.array([1, 2, 3, 4, 5])

vector_col = np.array([ [1],
                        [2],
                        [3] ])

## 1.2 Creating matrix

We can create matrix just using array and it's more common and right decision. However, Numpy has its own matrix structure, which shouldn't be used a lot because most of the numpy functions return arrays instead of matrices.

The code below will create matrix using different data structures. The matrix will have 3 rows with 2 columns.

```
[[1, 2],
 [1, 2],
 [1, 2]]
```


In [7]:
matrix_arr = np.array([[1, 2],
                      [1, 2],
                      [1, 2]])

matrix_obj = np.mat([[1, 2],
                    [1, 2],
                    [1, 2]])

## 1.3 Sparse Matrices

If we have data with with a predominant amount of null(zero) values, it's better to use sparse matrices which give us possibility to store data in more efficient way. To start using sparse matrices we will use library **scipy**.

There are seven available sparse matrix types:

    csc_matrix: Compressed Sparse Column format
    csr_matrix: Compressed Sparse Row format
    bsr_matrix: Block Sparse Row format
    lil_matrix: List of Lists format
    dok_matrix: Dictionary of Keys format
    coo_matrix: COOrdinate format (aka IJV, triplet format)
    dia_matrix: DIAgonal format

In [17]:
from scipy import sparse

In [81]:
sparse.csc_matrix?

In [92]:
def matrix_info(sparse_matrix, name):
    print(name)
    print(sparse_matrix)
    print('data: ' + str(sparse_matrix.data))
    print('ndim:' + str(sparse_matrix.ndim))
    try:
        print('indices: ' + str(sparse_matrix.indices))
    except Exception:
        print('indice: none')
        
    try:
        print('indptr: ' + str(sparse_matrix.indptr))
    except Exception:
        print('indptr: none')

    print(20 * '-')

In [93]:
matrix = np.array([[1, 2, 0], [0, 0, 3], [4, 0, 5]])

matrices = {
    'CSR': sparse.csr_matrix(matrix),
    'CSC': sparse.csc_matrix(matrix),
    'BSR': sparse.bsr_matrix(matrix),
    'LIL': sparse.lil_matrix(matrix),
    'COO': sparse.coo_matrix(matrix),
    'DIA': sparse.dia_matrix(matrix)
}

for key, value in matrices.items():
    matrix_info(value, key)

CSR
  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
data: [1 2 3 4 5]
ndim:2
indices: [0 1 2 0 2]
indptr: [0 2 3 5]
--------------------
CSC
  (0, 0)	1
  (2, 0)	4
  (0, 1)	2
  (1, 2)	3
  (2, 2)	5
data: [1 4 2 3 5]
ndim:2
indices: [0 2 0 1 2]
indptr: [0 2 3 5]
--------------------
BSR
  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
data: [[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]
ndim:2
indices: [0 1 2 0 2]
indptr: [0 2 3 5]
--------------------
LIL
  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
data: [list([1, 2]) list([3]) list([4, 5])]
ndim:2
indice: none
indptr: none
--------------------
COO
  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
data: [1 2 3 4 5]
ndim:2
indice: none
indptr: none
--------------------
DIA
  (2, 0)	4
  (0, 0)	1
  (2, 2)	5
  (0, 1)	2
  (1, 2)	3
data: [[4 0 0]
 [1 0 5]
 [0 2 3]]
ndim:2
indice: none
indptr: none
--------------------


method **todense()** return a dense matrix representation of this matrix.

In [91]:
print(matrices['CSC'])
print(20 * '-')
print(matrices['CSC'].todense())

  (0, 0)	1
  (2, 0)	4
  (0, 1)	2
  (1, 2)	3
  (2, 2)	5
--------------------
[[1 2 0]
 [0 0 3]
 [4 0 5]]
